FROM       registry.epoint.com.cn/base/epoint_alpine_tomcat:v1.11
MAINTAINER Shj test <shaojun@epoint.com.cn>
#tomcat
COPY  App  /usr/local/tomcat/webapps/AccessControl
ENV appbasepath /usr/local/tomcat 
